### ISSUE TITLE
Problems with version 2.4.15 and slider

### ISSUE THREAD

**Issue by prsolucoes** [ColorlibHQ/AdminLTE#2201] opened 2019-08-11 01:21 UTC
Problems with version 2.4.15 and slider

### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  2.4.15
* Operating System:  macos
* Browser (Version):  Chrome (Latest)

### Description:

Im trying to use version **2.4.15** but getting error:

```
make composer-update docker=1
docker exec y2aa_php_fpm composer update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bower-asset/admin-lte 2.4.15 -> satisfiable by bower-asset/admin-lte[v2.4.15].
    - bower-asset/admin-lte v2.4.15 requires bower-asset/bootstrap-slider 879-alpha98 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
make: *** [composer-update] Error 2
```

My composer:

https://github.com/prsolucoes/yii2-app-advanced/blob/mega-update/composer.json

Thanks for any help.

**Comment by REJack** [comment] 2019-08-11 08:58
It‘s caused by `"minimum-stability": "stable"` in your composer.json, you would need "dev" instead of "stable" for now, I've added a fix for this coming with the next release.

**Comment by prsolucoes** [comment] 2019-08-11 09:01
Hi,

Thanks for answer. I will wait for this fix because that project is tested and used in other projects, need be working with stable.

Thanks.

**Comment by REJack** [comment] 2019-08-13 11:07
v2.4.16 is released, you can update it.

**Closed by REJack** 2019-08-13 11:07 UTC
Labels: Bug, v2

**Comment by prsolucoes** [comment] 2019-08-13 18:14
Error:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/admin-lte 2.4.16 exists as bower-asset/admin-lte[v3.0.0-beta.2, v3.0.0-beta.1, v3.0.0-alpha.2, v3.0.0-alpha1, v2.4.15, v2.4.14, v2.4.13, v2.4.12, v2.4.11, v2.4.10, v2.4.9, v2.4.8, v2.4.7, v2.4.6, v2.4.5, v2.4.4, v2.4.3, v2.4.2, v2.4.1, v2.4.0, v2.4.0-RC1, v2.4.0-beta1, v2.4.0-alpha1, v2.3.11, v2.3.10, v2.3.9, v2.3.8, v2.3.7, v2.3.6, v2.3.5, v2.3.4, v2.3.3, v2.3.2, v2.3.1, v2.3.0, v2.2.1, v2.2.0, v2.1.2, 2.1.1, 2.1.0, v2.1.0-beta1, v2.1.0-alpha1, v2.0.5, v2.0.4, v2.0.3, v2.0.2, v2.0.1, v2.0.0, 1.3.1, 1.3.0, 1.2.1-patch1, v1.2.1, 1.2, 1.1, 1.0, 0.1, dev-master, 2.x-dev, dev-v3-dev] but these are rejected by your constraint.

make: *** [php-composer-update] Error 2
```
