### ISSUE TITLE
[RELEASE] AdminLTE version 3.1.0

### ISSUE THREAD

**Issue by deepak458** [ColorlibHQ/AdminLTE#2646] opened 2020-04-11 05:21 UTC
@REJack we are waiting for v3.1.0 from long time, let us know some date or month of this

**Comment by danny007in** [comment] 2020-04-11 23:49
If every forks contribute 

then it will soon

**Comment by REJack** [comment] 2020-04-13 14:14
I start soon with the whole v3.1 changes and my first milestone will be the RTL support, I need also to create the new adminlte.io page that's why I have some lack of time (+ the current situation is quite hard for me).

**Comment by GerryGe** [comment] 2020-04-17 09:55
> I start soon with the whole v3.1 changes and my first milestone will be the RTL support, I need also to create the new adminlte.io page that's why I have some lack of time (+ the current situation is quite hard for me).

Stay safe. Stay healthy.💪

**Comment by behiunforgiven** [comment] 2020-04-18 05:51
@REJack Can you estimate the release date?

**Comment by saeidakbari** [comment] 2020-05-19 14:10
@REJack Any good news here?

**Comment by REJack** [comment] 2020-05-19 20:19
At the moment I have no release date 😞, but I look over it in the next days and start with the RTL support first (hardest part of v3.1).

**Comment by deepak458** [comment] 2020-07-07 09:09
Hello @REJack is there any update on V3.1.0 ?

**Comment by REJack** [comment] 2020-07-07 12:13
I've started with the development, but at the moment I have no ETA for the release I hope for 1.9.2020 but I'm not sure. If I get some help with PR's it will be faster 😄

And it looks like I skip the RTL support caused by some problems with the RTL Bootstrap packages.

**Comment by MacGyer** [comment] 2020-08-31 12:04
@REJack any news here? Would love to see 3.1 arriving. 
Any help besides CSS stuff (I am back end developer) needed?

**Comment by REJack** [comment] 2020-11-26 07:36
AdminLTE v3.1.0-rc is out please test it and give me results, then I can release v3.1.0 soon.

**Comment by muhanadali100** [comment] 2020-12-21 00:38
Please RTL Support in 3.1.0 next update release

**Comment by REJack** [comment] 2020-12-21 01:04
Nope RTL will come with v4 (BS5)

**Comment by muhanadali100** [comment] 2020-12-22 01:59
> 
> 
> Nope RTL will come with v4 (BS5)

Release Date ??

**Comment by MacGyer** [comment] 2020-12-22 15:08
> Release Date ??

@muhanadali100 let 3.1.0 be finished.

And if you so desperately need the RTL feature, consider donating or active help

**Comment by medeepaksaini** [comment] 2021-02-03 10:27
@REJack when you are planning to release it.

**Comment by danny007in** [comment] 2021-02-19 05:39
@REJack u can release after 
- merging https://github.com/ColorlibHQ/AdminLTE/pull/3403
- and will create another Docs PR

**Comment by REJack** [comment] 2021-02-19 05:47
@danny007in 👌 I will do some final tests later, when you will finish with the new docs PR? ^^

**Comment by danny007in** [comment] 2021-02-19 06:10
> 
> 
> @danny007in 👌 I will do some final tests later, when you will finish with the new docs PR? ^^

within 1 hours

**Comment by danny007in** [comment] 2021-02-19 12:04
@REJack i have tried last week to covert to typescript and found some bugs
So can we convert it to typescript and force compile it

**Comment by medeepaksaini** [comment] 2021-02-21 03:15
@REJack Any update on release date...?

and when you will start working on it....!!!!

**Comment by danny007in** [comment] 2021-02-21 13:46
@REJack i am converting this to typescript

**Comment by REJack** [comment] 2021-02-21 13:56
> @REJack i am converting this to typescript

No, start with the SCSS Variables and extra Classes like custom textcolor etc. I work much with with TS and have already started with the conversion.

**Comment by danny007in** [comment] 2021-02-21 14:20
ok
i am pausing every thing now, let discuss after 3.1.0 release 😃

**Comment by WinterSilence** [comment] 2021-02-22 19:30
bug: 
demo.js: `.replace('navbar-', 'bg-').replace('accent-', 'bg-')` it's bad solution -`,bg-...` can use background colors not same to `.navbar-...`, check screen - `Brand Logo Variants` have 2 dark gray colors.
![изображение](https://user-images.githubusercontent.com/3521094/108759108-fbfc7780-755c-11eb-8672-38e9813f36a6.png)

**Comment by danny007in** [comment] 2021-02-23 07:29
@WinterSilence https://github.com/ColorlibHQ/AdminLTE/releases/tag/v3.1.0-rc check

**Comment by WinterSilence** [comment] 2021-02-23 16:05
@ danny007in this problem not fixed etc.

**Comment by REJack** [comment] 2021-02-23 16:25
It’s not important to fix, since it’s only for demo purposes and not for production use plus it will completly reworked with v4.

**Comment by aldycool** [comment] 2021-02-26 07:49
> @REJack Any update on release date...?
> 
> and when you will start working on it....!!!!

OMG you're so annoying... :satisfied: dude, why don't you help instead of whining 😎

**Comment by MacGyer** [comment] 2021-02-26 08:27
@aldycool Word! Thx.

**Comment by danny007in** [comment] 2021-02-27 09:47
@REJack can i make label as https://github.com/twbs/bootstrap/labels?page=2&sort=name-asc because its look simple and understandable to newbies

**Comment by REJack** [comment] 2021-02-27 09:54
labels like what? we should have all needed :D and i like the prefix in front of the labels

**Comment by danny007in** [comment] 2021-02-27 09:57
> 
> 
> labels like what? we should have all needed :D and i like the prefix in front of the labels

Ok i will enhance like this 😃

**Comment by REJack** [comment] 2021-02-27 10:00
Ok 👌🏼 but don't delete and recreate them :D otherwise we need to assign them again to issues ^^

**Comment by LucivalSoares** [comment] 2021-03-02 16:44
Quando abrimos o submenu level 3, e o a opção "Sidebar nav child hide on collapse" está ativa, e vamos abrir um menu level 3 os menus ficam tremendo, porque? há uma correção pra isso?

**Comment by LucivalSoares** [comment] 2021-03-02 16:46
When we open the submenu of level 3, and the option "Sidebar nav child hide when collapsing" is active, and we are going to open a level 3 menu, the menus are shaking, why? is there a correction for that?

**Comment by danny007in** [comment] 2021-03-02 16:57
> 
> 
> When we open the submenu of level 3, and the option "Sidebar nav child hide when collapsing" is active, and we are going to open a level 3 menu, the menus are shaking, why? is there a correction for that?

create it as separate issue 😄

**Comment by kernelogic** [comment] 2021-03-15 20:00
Is there documentation for v3? Or is it the same as v2? I noticed bootstrap has been upgraded to v4, is it the LTEV2 doc still apply?

**Comment by danny007in** [comment] 2021-03-15 20:43
> 
> 
> Is there documentation for v3? Or is it the same as v2? I noticed bootstrap has been upgraded to v4, is it the LTEV2 doc still apply?

https://adminlte.io/docs/3.1/

**Comment by medeepaksaini** [comment] 2021-03-20 10:55
@REJack can we release it toady ?

**Comment by danny007in** [comment] 2021-03-20 15:27
> 
> 
> @REJack can we release it toady ?

No,
 still, 2 main issue to clear.

**Comment by REJack** [comment] 2021-03-20 17:35
@danny007in I see only #3498, can you set the `state:pending` label to the others? I fix them in 1-2hrs after cooking and eating 🤣. Your dark-mode PR is done and merged.

**Comment by medeepaksaini** [comment] 2021-03-22 07:07
@REJack i think it's time to release v 3.1.0 all Todo are done

also you can create new branch for V4 to start basic

**Comment by REJack** [comment] 2021-03-22 07:27
I'm already in the release preparations 😂 I guess the release is in max 1 hour online.

**Comment by MacGyer** [comment] 2021-03-22 08:47
@medeepaksaini and all other making demand on releases and schedules:

Consider donating or active collaboration. All you do is whining and claiming which is/must be really annoying for someone dedicating his spare time to an Open Source project.

@REJack keep up the good work. Looking forward to the new release *hooray*

Cheers

**Comment by REJack** [comment] 2021-03-22 11:31
🎉🎉🎉  AdminLTE v3.1.0 is online 🎉🎉🎉

**Comment by spizzo14** [comment] 2021-03-22 12:04
Awesome great job! Jack did you get my email? Also are you still using the sharedarraybuffer ? Google had a post about it https://developers.google.com/search/blog/2021/03/sharedarraybuffer-notes

**Comment by REJack** [comment] 2021-03-22 12:35
@spizzo14 yep I got your mail and awnsered already may it's in junk 🤣, only dropzone.js uses SharedArrayBuffer.

**Comment by spizzo14** [comment] 2021-03-22 13:57
> @spizzo14 yep I got your mail and awnsered already may it's in junk 🤣, only dropzone.js uses SharedArrayBuffer.

didn't get any email back

**Comment by navtek** [comment] 2021-03-22 18:21
Congratulations!!! Please let us know how we can donate or sponsor this amazing project.

**Comment by saif31617** [comment] 2021-04-26 12:25
```
zone-evergreen.js:182 Uncaught TypeError: Cannot read property 'getContext' of undefined
    at HTMLDocument.<anonymous> (dashboard2.js:17)
    at mightThrow (jquery.js:3766)
    at process (jquery.js:3834)
    at timer (zone-evergreen.js:2561)
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)
    at Zone.runTask (zone-evergreen.js:178)
    at invokeTask (zone-evergreen.js:487)
    at ZoneTask.invoke (zone-evergreen.js:476)
    at data.args.<computed> (zone-evergreen.js:2541)
(anonymous) @ dashboard2.js:17
mightThrow @ jquery.js:3766
process @ jquery.js:3834
timer @ zone-evergreen.js:2561
invokeTask @ zone-evergreen.js:406
runTask @ zone-evergreen.js:178
invokeTask @ zone-evergreen.js:487
ZoneTask.invoke @ zone-evergreen.js:476
data.args.<computed> @ zone-evergreen.js:2541
setTimeout (async)
scheduleTask @ zone-evergreen.js:2543
scheduleTask @ zone-evergreen.js:393
scheduleTask @ zone-evergreen.js:221
scheduleMacroTask @ zone-evergreen.js:244
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:679
(anonymous) @ zone-evergreen.js:2585
proto.<computed> @ zone-evergreen.js:975
jQuery.readyException @ jquery.js:4058
(anonymous) @ jquery.js:4078
mightThrow @ jquery.js:3766
process @ jquery.js:3834
timer @ zone-evergreen.js:2561
invokeTask @ zone-evergreen.js:406
runTask @ zone-evergreen.js:178
invokeTask @ zone-evergreen.js:487
ZoneTask.invoke @ zone-evergreen.js:476
data.args.<computed> @ zone-evergreen.js:2541
setTimeout (async)
scheduleTask @ zone-evergreen.js:2543
scheduleTask @ zone-evergreen.js:393
scheduleTask @ zone-evergreen.js:221
scheduleMacroTask @ zone-evergreen.js:244
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:679
(anonymous) @ zone-evergreen.js:2585
proto.<computed> @ zone-evergreen.js:975
(anonymous) @ jquery.js:3872
fire @ jquery.js:3500
fireWith @ jquery.js:3630
fire @ jquery.js:3638
fire @ jquery.js:3500
fireWith @ jquery.js:3630
process @ jquery.js:3854
timer @ zone-evergreen.js:2561
invokeTask @ zone-evergreen.js:406
runTask @ zone-evergreen.js:178
invokeTask @ zone-evergreen.js:487
ZoneTask.invoke @ zone-evergreen.js:476
data.args.<computed> @ zone-evergreen.js:2541
setTimeout (async)
scheduleTask @ zone-evergreen.js:2543
scheduleTask @ zone-evergreen.js:393
scheduleTask @ zone-evergreen.js:221
scheduleMacroTask @ zone-evergreen.js:244
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:679
(anonymous) @ zone-evergreen.js:2585
proto.<computed> @ zone-evergreen.js:975
(anonymous) @ jquery.js:3872
fire @ jquery.js:3500
fireWith @ jquery.js:3630
fire @ jquery.js:3638
fire @ jquery.js:3500
fireWith @ jquery.js:3630
ready @ jquery.js:4110
timer @ zone-evergreen.js:2561
invokeTask @ zone-evergreen.js:406
runTask @ zone-evergreen.js:178
invokeTask @ zone-evergreen.js:487
ZoneTask.invoke @ zone-evergreen.js:476
data.args.<computed> @ zone-evergreen.js:2541
setTimeout (async)
scheduleTask @ zone-evergreen.js:2543
scheduleTask @ zone-evergreen.js:393
scheduleTask @ zone-evergreen.js:221
scheduleMacroTask @ zone-evergreen.js:244
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:679
(anonymous) @ zone-evergreen.js:2585
proto.<computed> @ zone-evergreen.js:975
(anonymous) @ jquery.js:4131
(anonymous) @ jquery.js:36
(anonymous) @ `jquery.js:40`


i am getting this error  what should be the probable solution 

```

**Comment by danny007in** [comment] 2021-04-26 12:27
> 
> 
> ```
> zone-evergreen.js:182 Uncaught TypeError: Cannot read property 'getContext' of undefined
>     at HTMLDocument.<anonymous> (dashboard2.js:17)
>     at mightThrow (jquery.js:3766)
>     at process (jquery.js:3834)
>     at timer (zone-evergreen.js:2561)
>     at ZoneDelegate.invokeTask (zone-evergreen.js:406)
>     at Zone.runTask (zone-evergreen.js:178)
>     at invokeTask (zone-evergreen.js:487)
>     at ZoneTask.invoke (zone-evergreen.js:476)
>     at data.args.<computed> (zone-evergreen.js:2541)
> (anonymous) @ dashboard2.js:17
> mightThrow @ jquery.js:3766
> process @ jquery.js:3834
> timer @ zone-evergreen.js:2561
> invokeTask @ zone-evergreen.js:406
> runTask @ zone-evergreen.js:178
> invokeTask @ zone-evergreen.js:487
> ZoneTask.invoke @ zone-evergreen.js:476
> data.args.<computed> @ zone-evergreen.js:2541
> setTimeout (async)
> scheduleTask @ zone-evergreen.js:2543
> scheduleTask @ zone-evergreen.js:393
> scheduleTask @ zone-evergreen.js:221
> scheduleMacroTask @ zone-evergreen.js:244
> scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:679
> (anonymous) @ zone-evergreen.js:2585
> proto.<computed> @ zone-evergreen.js:975
> jQuery.readyException @ jquery.js:4058
> (anonymous) @ jquery.js:4078
> mightThrow @ jquery.js:3766
> process @ jquery.js:3834
> timer @ zone-evergreen.js:2561
> invokeTask @ zone-evergreen.js:406
> runTask @ zone-evergreen.js:178
> invokeTask @ zone-evergreen.js:487
> ZoneTask.invoke @ zone-evergreen.js:476
> data.args.<computed> @ zone-evergreen.js:2541
> setTimeout (async)
> scheduleTask @ zone-evergreen.js:2543
> scheduleTask @ zone-evergreen.js:393
> scheduleTask @ zone-evergreen.js:221
> scheduleMacroTask @ zone-evergreen.js:244
> scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:679
> (anonymous) @ zone-evergreen.js:2585
> proto.<computed> @ zone-evergreen.js:975
> (anonymous) @ jquery.js:3872
> fire @ jquery.js:3500
> fireWith @ jquery.js:3630
> fire @ jquery.js:3638
> fire @ jquery.js:3500
> fireWith @ jquery.js:3630
> process @ jquery.js:3854
> timer @ zone-evergreen.js:2561
> invokeTask @ zone-evergreen.js:406
> runTask @ zone-evergreen.js:178
> invokeTask @ zone-evergreen.js:487
> ZoneTask.invoke @ zone-evergreen.js:476
> data.args.<computed> @ zone-evergreen.js:2541
> setTimeout (async)
> scheduleTask @ zone-evergreen.js:2543
> scheduleTask @ zone-evergreen.js:393
> scheduleTask @ zone-evergreen.js:221
> scheduleMacroTask @ zone-evergreen.js:244
> scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:679
> (anonymous) @ zone-evergreen.js:2585
> proto.<computed> @ zone-evergreen.js:975
> (anonymous) @ jquery.js:3872
> fire @ jquery.js:3500
> fireWith @ jquery.js:3630
> fire @ jquery.js:3638
> fire @ jquery.js:3500
> fireWith @ jquery.js:3630
> ready @ jquery.js:4110
> timer @ zone-evergreen.js:2561
> invokeTask @ zone-evergreen.js:406
> runTask @ zone-evergreen.js:178
> invokeTask @ zone-evergreen.js:487
> ZoneTask.invoke @ zone-evergreen.js:476
> data.args.<computed> @ zone-evergreen.js:2541
> setTimeout (async)
> scheduleTask @ zone-evergreen.js:2543
> scheduleTask @ zone-evergreen.js:393
> scheduleTask @ zone-evergreen.js:221
> scheduleMacroTask @ zone-evergreen.js:244
> scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:679
> (anonymous) @ zone-evergreen.js:2585
> proto.<computed> @ zone-evergreen.js:975
> (anonymous) @ jquery.js:4131
> (anonymous) @ jquery.js:36
> (anonymous) @ `jquery.js:40`
> 
> 
> 
> ### **i am getting this error  what should be the probable solution** 
> ```

Create new issue for this
@saif31617 😃

**Closed by danny007in** 2021-04-26 12:27 UTC
Labels: type:news, version:3.1.x
