### ISSUE TITLE
Alert with fade and show classes, when dismiss the space reserved for it still in screen.

### ISSUE THREAD

**Issue by SmileYzn** [ColorlibHQ/AdminLTE#2195] opened 2019-08-08 03:44 UTC
### Issue type:
- [x] Bug report       

### Environment:
* AdminLTE Version:  3 (Lastest beta)
* Operating System:  Windows 8.1
* Browser (Version):  Chrome (Latest)

### Description:

Alert with fade and show classes, when dismiss the space reserved for it still in screen.

Example: 
![Example image](https://i.imgur.com/qBfxaEO.png)

I hope this is not a bootstrap bug :laughing: 

Thanks for hard work, the devil is in details

**Comment by REJack** [comment] 2019-08-08 06:57
I can't reproduce this, if I add `.fade` & `.show` to a alert and click on close it will be removed by bootstrap's alert script.

Can you please add a example html from this alert?

**Comment by SmileYzn** [comment] 2019-08-08 22:05
Im using with a custom PHP system, i can send a markup generated by system from view source code on chrome?

anyway here is the generated HTML data: https://pastebin.com/HDqLsFQT

**Comment by REJack** [comment] 2019-08-09 06:57
I've checked the html markup, its perfect and works. May you have an javascript error that's blocks the alert removing, please check your console if there occurs an error.

**Comment by SmileYzn** [comment] 2019-08-09 13:01
Nothing in console :|

I guess i forgot someting on code, it just works normally without these classes.
Also i just removed the fade show classes from alert and now is working fine to me.

Also i tested with default template adding these classes on general.html page, and works fine too.
:open_mouth: 

https://i.imgur.com/sSHIXDT.png

anyway thanks bro

**Closed** 2019-08-09 13:02 UTC
Labels: Bug, v3
