### ISSUE TITLE
Search don't work with me

### ISSUE THREAD

**Issue by muhanadali100** [ColorlibHQ/AdminLTE#3672] opened 2021-05-09 00:54 UTC
Search don't work ... i have the last update
![Screenshot_2021-05-09 404 Not Found](https://user-images.githubusercontent.com/31727156/117557310-2a78f180-b07a-11eb-89c8-b18fa638e080.png) 

![Screenshot_2021-05-09 ADVANCED NET](https://user-images.githubusercontent.com/31727156/117557309-2947c480-b07a-11eb-874a-c0332e375c42.png)

**Comment by danny007in** [comment] 2021-05-09 12:48
its issue of php,
run wamp or xamp or php server

**Comment by danny007in** [comment] 2021-05-09 12:49
add full url in sidebar anchor tag

**Comment by danny007in** [comment] 2021-05-09 12:53
indirectly duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3556

**Comment by danny007in** [comment] 2021-05-10 12:42
add full url
like from `http://localhost/`

**Comment by muhanadali100** [comment] 2021-05-15 07:58
> 
> 
> add full url
> like from `http://localhost/`

http://15.15.15.7/index.php%3Fcont%3Dwifi_ap

these the link showing to me

but the correct link is
http://15.15.15.7/index.php?cont=wifi_ap

**Comment by danny007in** [comment] 2021-05-15 17:08
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3556
wait for AdminLTE v3.2.0

**Comment by muhanadali100** [comment] 2021-05-16 13:35
> 
> 
> duplicate of #3556
> bug if fixed.
> wait for AdminLTE v3.2.0

ok

**Closed** 2021-05-16 18:12 UTC
Labels: other:duplicate, type:bug, version:3.1.x
