### ISSUE TITLE
adminLTE 3.0 beta 2 sidebar-collapse sidebar-open bug

### ISSUE THREAD

**Issue by nikonov91-dev** [ColorlibHQ/AdminLTE#2393] opened 2019-11-08 10:28 UTC
**Describe the bug**
sidebar bug found on sidebar accordion click but css classes havent been changed from sidebar-collapse to sidebar-open

**To Reproduce**
1. Go to any page with sidebar-mini
2. Click on collapse the sidebar clicking at burger btn
3. click on accordion element (or any other element at collapsed sidebar) to get the sidebar opened
4. See the sidebar-mini class doesnt change from 'sidebar-collapse' to 'sidebar-open'

**Expected behavior**
 the sidebar-mini class must change from 'sidebar-collapse' to 'sidebar-open' on any element click at collapsed sidebar

**video**
[see the video](https://drive.google.com/file/d/1me4_6Z_aqvm9ZevJc-CXQZ8eHoR5FTph/view?usp=sharing)

**Environment (please complete the following information):**
 - AdminLTE v3.0.0 beta 2
 - Chrome 78
- Mozilla 68

**Comment by REJack** [comment] 2019-11-08 11:52
This is not a bug, it's the wanted behavior, but I'll add a option for this behavior.

**Comment by REJack** [comment] 2019-11-13 13:11
I've added a expandSidebar option to Treeview, it will released with v3.0.1

**Closed** 2019-11-20 08:44 UTC
Labels: related:js, state:released, type:enhancement, version:3.x
