### ISSUE TITLE
[BUG] Class "menu-open" broke nested levels on treeview

### ISSUE THREAD

**Issue by forxer** [ColorlibHQ/AdminLTE#3425] opened 2021-02-15 20:21 UTC
**Describe the bug**

When the "menu-open" class is applied to a first level menu that contains sub-levels, those sub-levels are abnormally open as well, which should not be the case.

Continued from #3396  

**To Reproduce**

Download https://github.com/ColorlibHQ/AdminLTE/releases/tag/v3.1.0-rc

In index3.html add "menu-open" class to first level like this :

```html
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Level 1</p>
            </a>
          </li>
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-circle"></i>
              <p>
                Level 1
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Level 2</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>
                    Level 2
                    <i class="right fas fa-angle-left"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-dot-circle nav-icon"></i>
                      <p>Level 3</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-dot-circle nav-icon"></i>
                      <p>Level 3</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="#" class="nav-link">
                      <i class="far fa-dot-circle nav-icon"></i>
                      <p>Level 3</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Level 2</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Level 1</p>
            </a>
          </li>
```

The following levels  **should be closed**.

![image](https://user-images.githubusercontent.com/407917/107989823-5c2a7100-6fd3-11eb-9d94-0d3c02d15462.png)

**Expected behavior**

The red box should not appear. 

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.x
- Operating System:  Windows 10
- Browser (Version): Firefox (85)

**Comment by danny007in** [comment] 2021-02-16 08:57
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3396#issuecomment-779418953

**Closed by danny007in** 2021-02-16 08:57 UTC
Labels: other:duplicate, type:bug, version:3.1.x
