### ISSUE TITLE
morris has some bug

### ISSUE THREAD

**Issue by LJNjust** [ColorlibHQ/AdminLTE#2010] opened 2018-10-19 03:21 UTC
I find morris has some bug；
when I close leftnav，the morris pic will not change。so The right side of the picture is partially blank。

**Comment by REJack** [comment] 2019-07-10 20:21
I can't reproduce, I'll close this issue but you can reopen it if you can give me more infos I can check it again.

**Closed by REJack** 2019-07-10 20:21 UTC
