### ISSUE TITLE
.custom-select in dark dark mode not showing arrows

### ISSUE THREAD

**Issue by aaronhudon** [ColorlibHQ/AdminLTE#3644] opened 2021-04-29 23:47 UTC
**Describe the bug**
Applying the `.custom-select` Bootstrap class to a `select` element in dark mode does not render the drop down arrow

**Screenshots**
![image](https://user-images.githubusercontent.com/4406811/116631836-9e90f800-a90a-11eb-96b6-b837cabf3468.png)
![image](https://user-images.githubusercontent.com/4406811/116631715-68537880-a90a-11eb-89cf-1b3375ecd00d.png)

**Environment (please complete the following information):**
- AdminLTE Version:  3.1.0
- Browser (Version): Chrome latest

**Comment by danny007in** [comment] 2021-04-30 09:10
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3571

**Closed by danny007in** 2021-04-30 09:10 UTC
Labels: other:duplicate, type:bug, version:3.1.x
