### ISSUE TITLE
Iframe optimization issues

### ISSUE THREAD

**Issue by pucoder** [ColorlibHQ/AdminLTE#3574] opened 2021-04-08 03:04 UTC
Is it possible to set a TAB that is selected by default on the iframe page? When you refresh the page, the TAB that is selected should not disappear

**Comment by danny007in** [comment] 2021-04-08 03:47
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3408

**Closed by danny007in** 2021-04-08 03:47 UTC
Labels: type:bug, version:3.1.x
