### ISSUE TITLE
[BUG] min-height for `.content-wrapper` not adequately calculated

### ISSUE THREAD

**Issue by djidji01** [ColorlibHQ/AdminLTE#3123] opened 2020-11-07 09:08 UTC
**Describe the bug**
The the opened `.control-sidebar-content` overlap the footer. 

**To Reproduce**
Open the Dashboard 3 `index3.html` page, open the control-sidebar 
1. Go to `index3.html`
2. Click on button to toggle the right sidebar  "control-sidebar"
3. Scroll down to interface between control-sidebar and the footer
4. See overlapped control-sidebar-content and footer 

**Expected behavior**
should be a clear interface between control-sidebar and the footer

**Screenshots**

![image](https://user-images.githubusercontent.com/19886674/98437264-87a2e300-20e9-11eb-99c2-a16888b0f5e9.png)

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0-pre (master)
- Operating System:  windows 10
- Browser (Version): Firefox(latest)

**Additional context**

**Comment by danny007in** [comment] 2020-11-22 23:35
follow this link [https://github.com/ColorlibHQ/AdminLTE/issues/3137](https://github.com/ColorlibHQ/AdminLTE/issues/3137)
You may get answer

**Comment by REJack** [comment] 2020-11-24 06:52
Duplicate of #3137

**Closed by REJack** 2020-11-24 06:52 UTC
Labels: type:bug, version:3.x
