### ISSUE TITLE
[BUG] Cards: color variations for outlines are not being applied

### ISSUE THREAD

**Issue by malle-pietje** [ColorlibHQ/AdminLTE#2381] opened 2019-11-03 15:42 UTC
**Describe the bug**
On the demo page
https://adminlte.io/themes/v3/pages/widgets.html
The cards using outlines with color variations don't have any color styles applied to the outlines.

**To Reproduce**
Go to
https://adminlte.io/themes/v3/pages/widgets.html

or
https://adminlte.io/docs/3.0/components/cards.html

**Expected behavior**
Styled outlines

**Screenshots**
![cards](https://user-images.githubusercontent.com/12016131/68087675-649b7e80-fe58-11e9-856e-6be6215b54a5.png)

**Environment (please complete the following information):**
 - AdminLTE Version: v3.0.0
 - Operating System: Windows 10
 - Browser (Version): Chrome (Latest)

**Comment by REJack** [comment] 2019-11-04 08:49
Duplicate of #2378

**Closed by REJack** 2019-11-04 08:49 UTC
Labels: other:duplicate, type:bug, version:3.x

**Comment by malle-pietje** [comment] 2019-11-04 09:47
Thanks, I realized this after I submitted the issue
