### ISSUE TITLE
[BUG] can't load the page into iframe.

### ISSUE THREAD

**Issue by bdelmaik** [ColorlibHQ/AdminLTE#3236] opened 2020-12-20 23:51 UTC
You can't load the page into iframe, it's blank or loading. The page cannot be loaded into iframe, blank, or loaded. It does not open any other links. iframe from the navigation bar. Can I change the mode from Iframe to boostrap Responsive Iframe for tabs?

**Comment by danny007in** [comment] 2020-12-21 14:27
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3233

**Closed** 2020-12-22 09:18 UTC
Labels: type:bug, version:3.x
