### ISSUE TITLE
[LICENSE] Including AdminLTE in OpenSource project

### ISSUE THREAD

**Issue by stephb9959** [ColorlibHQ/AdminLTE#3381] opened 2021-02-04 18:12 UTC
Hi,

Is it permissible to include AdminLTE-based UI as part of an open-source application? Does it require purchasing any license plan from the authors? 

Thank you.

**Comment by danny007in** [comment] 2021-02-04 20:13
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3307

**Closed by danny007in** 2021-02-04 20:13 UTC
