### ISSUE TITLE
[BUG] It cannot display the page "in iframe mode " when use python with flask .

### ISSUE THREAD

**Issue by qianlicao8000** [ColorlibHQ/AdminLTE#3295] opened 2021-01-10 09:33 UTC
**Describe the bug**
 It cannot display the left side menu linkiing page "in iframe mode " when use python with flask .

**Comment by danny007in** [comment] 2021-01-10 11:23
Give some more details regarding issue like code, images, gifs to solve issue

**Comment by qianlicao8000** [comment] 2021-01-10 12:43
In chrome “respect”source ,I find the code generated :the tab iframe's height is 0px.see the pic.
![caputure](https://user-images.githubusercontent.com/10287340/104123138-4bf3f600-5384-11eb-8c0c-e93c27104655.JPG)

**Comment by danny007in** [comment] 2021-01-10 12:47
Which version Of adminLTE

**Comment by danny007in** [comment] 2021-01-10 12:47
i mean rc to main

**Comment by qianlicao8000** [comment] 2021-01-10 12:48
Uploading 202111020467rec.mp4…

**Comment by qianlicao8000** [comment] 2021-01-10 12:48
AdminLTE-3.1.0-rc

**Comment by danny007in** [comment] 2021-01-10 12:50
> 
> 
> AdminLTE-3.1.0-rc

Check in master branch 'npm run dev'

**Comment by qianlicao8000** [comment] 2021-01-10 12:59
Not use npm,just download the git code,then use the code files in project .

**Comment by danny007in** [comment] 2021-01-10 13:02
It as fixed in master branch,
And will be released soon in stable version

**Closed by danny007in** 2021-01-10 13:02 UTC
Labels: type:bug, version:3.x

**Comment by qianlicao8000** [comment] 2021-01-10 13:04
OK,thanks .Hope the stable version.

**Comment by danny007in** [comment] 2021-01-10 13:06
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3266
