### ISSUE TITLE
[BUG] Layout-boxed with fixed-navbar not working

### ISSUE THREAD

**Issue by Zanoshky** [ColorlibHQ/AdminLTE#3742] opened 2021-06-01 18:33 UTC
**Describe the bug**
If you add layout-boxed to fixed-navbar the UI breaks.

**To Reproduce**
1. Add layout-boxed to body

**Expected behavior**
Should be fixed to the top without going out of the box

**Screenshots**
<img width="2661" alt="image" src="https://user-images.githubusercontent.com/8194241/120373345-8997f200-c318-11eb-8cee-0198b3c9ab7a.png">

**Environment (please complete the following information):**
- AdminLTE Version: 3.1.0
- Operating System:  macOS Catalina
- Browser (Version): Chrome (Latest)

**Additional context**

**Comment by danny007in** [comment] 2021-06-02 02:43
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3559

**Closed by danny007in** 2021-06-02 02:43 UTC
Labels: type:bug, version:3.1.x
