### ISSUE TITLE
Upgrade Font Awesome (to 5.0.8)

### ISSUE THREAD

**Issue by siemensikkema** [ColorlibHQ/AdminLTE#1833] opened 2018-03-08 12:42 UTC
### Issue type:
- [x] Feature request
- [ ] Bug report
- [ ] Documentation

### Environment:
* AdminLTE Version:  2.4.3
* Operating System: all
* Browser (Version): all

### Description:
Upgrade Font-awesome (to 5.0.8).

The current version integrated into AdminLTE is 4.7.0. This is also the latest version hosted by the Cloudflare CDN. Font Awesome have their own CDN which could possible be used but I'm not sure if their licensing is compatible: https://cdn.fontawesome.com.

**Comment by madl-ash** [comment] 2018-03-17 20:34
+1

**Comment by B0bbyD0llar** [comment] 2018-03-18 09:51
+1

**Comment by glazzara** [comment] 2018-03-18 20:13
+1

**Comment by daniele-athome** [comment] 2018-03-18 20:17
Please stop adding "+1" as comments, it only adds spam, use the reaction button to the original post. Thank you!

**Comment by B0bbyD0llar** [comment] 2018-03-19 08:35
@daniele-athome i dont think so.

**Comment by almasaeed2010** [comment] 2018-04-08 13:11
I haven't tested FA5 yet but it seems reasonable to support. This will be available in v3.

**Comment by dels07** [comment] 2018-04-11 03:09
The way they use svg sometimes make it hard to add custom styles, because svg is generated after document complete load, but there is an option to use webfont like the v4.x

**Comment by egmfrs** [comment] 2018-07-26 12:06
I've added a CDN reference for FA5 to my project but the hamburger menu icon no longer displays. It renders as the square / invalid character symbol. Anyone know how I can resolve this?

**Comment by iksaku** [comment] 2018-07-30 03:00
I've been working with FontAwesome 5 with AdminLTE v2.4(.x), CSS-based package of FA requires little updates on the [styling](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#styling).
Besides that, the "easy" way to get them working, is to use the SVG-based package. Most icon's positioning can be fixed by giving them a [transform](https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms) of `left-8`, `left-9` or `left-10`. 
Also, there are some other icons in elements which appear in a higher position than they should be, a transform of `down-1` is enough to most of the time to fix them, or use an kind CSS rule in the icon itself: `top: 0.2em`.

**Comment by rgomez90** [comment] 2018-08-07 16:28
@egmfrs notice that in version 5 they change class `fa` to `fas`, it may be your issue.

**Version 4**
![image](https://user-images.githubusercontent.com/12009909/43789115-7c7a4656-9a6f-11e8-83ad-fd8bc88cf660.png)
 
**Version 5**
![image](https://user-images.githubusercontent.com/12009909/43789144-8e04a308-9a6f-11e8-81b4-244728ae0fac.png)

**Comment by iksaku** [comment] 2018-08-07 17:07
@rgomez90 as stated in the [Upgrading from Version 4](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#changes) part of the documentation, the `fa` prefix fallsback to the new `fas` prefix. It shouldn't be an issue, unless the specific icon name changed.
And for @egmfrs's issue, the problem is that the `bars` icon in the template is referenced directly in the [LESS](https://github.com/almasaeed2010/AdminLTE/blob/d9e68301848a95dff2e2dbef6569e617a9b3fa30/build/less/header.less#L75) as a Unicode character, instead of being referenced with a `<span>` or `<I>` tag. You can actually override it with some custom CSS:
```css
.sidebar-toggle:before {
    content: none !important;
}
```

**Comment by egmfrs** [comment] 2018-08-08 12:40
I actually had to add a font-weight with the bars icon in order for it to display, which is a bug with fa 5

**Comment by cahpalencia** [comment] 2018-08-17 14:28
I just made a few changes to implement Add Button: https://pastebin.com/nQ1FUgfk

**Comment by maohieng** [comment] 2018-09-09 05:06
@iksaku, thank you. It works for me after I try integrate AdmintLTE 2.4.5 with fontAwesome 5.

**Comment by DL6ER** [comment] 2018-12-28 18:20
I was able to use AdminLTE4 with FontAwesome 5.6.3 by only adding the following line to my custom CSS:
```css
.sidebar-toggle:before {
    font-weight: 900;
    font-family: "Font Awesome 5 Free";
}
```

**Comment by mmucino1** [comment] 2019-02-06 03:20
> I was able to use AdminLTE4 with FontAwesome 5.6.3 by only adding the following line to my custom CSS:
> 
> ```css
> .sidebar-toggle:before {
>     font-weight: 900;
>     font-family: "Font Awesome 5 Free";
> }
> ```

Worked for AdminLTE v2 and FontAwesome V5.7.1

**Comment by REJack** [comment] 2019-05-28 08:06
I'v updated FontAwesome to v5.8.2 in AdminLTE v3-dev with #2110.

**Closed by REJack** 2019-05-28 08:06 UTC
Labels: Feature, v3
