### ISSUE TITLE
[FEATURE] Bootstrap 5 Support

### ISSUE THREAD

**Issue by keepgoingdev** [ColorlibHQ/AdminLTE#3329] opened 2021-01-18 10:01 UTC
Hi Development Team,
Thank you so much for your nice contribution to this amazing thing.

I used Admin LTE 2 for years and now I want to upgrade my site with Admin LTE 3.
But I wonder do you have any expected date or work progress for Bootstrap 5 Implementation?

Or Is it possible for me to use Bootstrap 5 with Admin LTE 3?

Thanks!

**Comment by danny007in** [comment] 2021-01-18 10:20
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/2855
And 
Discuss issue there regarding bs5 plz

**Closed by danny007in** 2021-01-18 10:20 UTC
Labels: type:enhancement, version:3.x
