### ISSUE TITLE
[BUG] sparklines seems unused

### ISSUE THREAD

**Issue by XhmikosR** [ColorlibHQ/AdminLTE#2805] opened 2020-06-05 08:32 UTC
...or wrongfully used

1. there's no jquery-sparkline plugin; there is a sparklines plugin but it's not used in charts/inline.html
2. it seems index.html loads sparklines but I don't know if it even uses the file: any unused assets (CSS/JS) should be removed from all pages

**Comment by REJack** [comment] 2020-07-24 16:31
The jquery-sparkline plugin isn't packed in AdminLTE since v3 but I missed to remove the link/script references.
I've added a demo for sparklines.js in charts/inline.html, a duplicate of the sparklines from the index.html.


These three little graphs are the sparklines from index.html :smile:
![grafik](https://user-images.githubusercontent.com/1554582/88413544-ab147d00-cddb-11ea-90c4-702d7e475d56.png)

**Closed** 2020-07-24 16:37 UTC
Labels: related:examples, state:pending, type:bug, version:3.x
