### ISSUE TITLE
[BUG] Errot while compiling using laravel webmix and npm

### ISSUE THREAD

**Issue by mboczek** [ColorlibHQ/AdminLTE#3577] opened 2021-04-09 15:38 UTC
**Error while compiling using "npm run production" in Laravel**
I'm using Laravel 6.20 and I have installed adminlte 3.1 with npm. When I compile adminlte using "npm run dev" everything is fine - no errors. But when I try  "npm run production" I get errors:

> WARNING in ./node_modules/admin-lte/build/scss/adminlte.scss (./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--8-4!./node_modules/sass-loader/dist/cjs.js??ref--8-5!./node_modules/admin-lte/build/scss/adminlte.scss)
> Module Warning (from ./node_modules/postcss-loader/src/index.js):
> Warning
> 
> (2383:3) Error in parsing SVG: Non-whitespace before first tag.
> Line: 0
> Column: 1
> Char: d
>  @ ./node_modules/admin-lte/build/scss/adminlte.scss 2:14-218
> 
> WARNING in ./node_modules/admin-lte/build/scss/adminlte.scss (./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--8-4!./node_modules/sass-loader/dist/cjs.js??ref--8-5!./node_modules/admin-lte/build/scss/adminlte.scss)
> Module Warning (from ./node_modules/postcss-loader/src/index.js):
> Warning
> 
> (2503:3) Error in parsing SVG: Non-whitespace before first tag.
> Line: 0
> Column: 1
> Char: d
>  @ ./node_modules/admin-lte/build/scss/adminlte.scss 2:14-218

**To Reproduce**
1. Install Laravel
2. Install adminlte with 'npm install admin-lte@^3.1 --save-dev'
3. Add 'mix.sass('node_modules/admin-lte/build/scss/adminlte.scss', 'public/css')' to webpack.mix.js
4. Run 'npm run production'

**Result**
I still get compiled adminlte.css file with size 1,29 MB, but I'm not sure if there's eveything as it should be or maybe it lacks some SVGs.

**Comment by danny007in** [comment] 2021-04-09 15:58
indirectly duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3530

**Comment by danny007in** [comment] 2021-04-28 17:14
solved in https://github.com/ColorlibHQ/AdminLTE/pull/3595

**Closed by danny007in** 2021-04-28 17:14 UTC
Labels: type:bug, version:3.1.x
