### ISSUE TITLE
[FEATURE] Support RTL for AdminLTE

### ISSUE THREAD

**Issue by 9iaashalaby** [ColorlibHQ/AdminLTE#3740] opened 2021-05-31 10:55 UTC
AdminLTE is one of the best free template, but we still must have to add support for RTL.

**Comment by danny007in** [comment] 2021-05-31 14:08
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/2236

**Closed by danny007in** 2021-05-31 14:08 UTC
Labels: type:enhancement, version:4.x
