### ISSUE TITLE
[BUG] duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3556

### ISSUE THREAD

**Issue by ozimstudio** [ColorlibHQ/AdminLTE#3606] opened 2021-04-18 19:11 UTC
**Describe the bug**

**To Reproduce**
1. Go to navbar search and type item to search
2. Click on search result with link e.g. index.php?ghjg=1
3. get error

**Expected behavior**
follow link

- AdminLTE Version:  v3.1.0
- Operating System:  any
- Browser (Version): firefox latest

**Additional context**
Problem is in string 
  $__default['default'](SELECTOR_SEARCH_RESULTS_GROUP).append(_this2._renderItem(escape(result.name), escape(result.link), result.path));

need to change to 
  $__default['default'](SELECTOR_SEARCH_RESULTS_GROUP).append(_this2._renderItem(escape(result.name), result.link, result.path));
and everything works fine. No need to "escape" here.

**Comment by danny007in** [comment] 2021-04-19 06:21
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3556

**Closed by danny007in** 2021-04-19 06:21 UTC
Labels: other:duplicate, type:bug, version:3.1.x
