### ISSUE TITLE
[FEATURE] Make the dark-mode rules opt-out

### ISSUE THREAD

**Issue by Joniras** [ColorlibHQ/AdminLTE#3664] opened 2021-05-05 11:53 UTC
# Why ?
I was creating themes for my application today and looked at the size my css files already have (Bootstrap, AdminLTE, Angular Material, and so on). As i did a deep-dive into my CSS Files i realized that .dark-mode is everywhere. It has more than 4k entries in the css file. 
The thing is: I dont need .dark-mode. I was able to opt-out pages and components i dont need but .dark-mode is everywhere and therefore difficult to remove.

# Suggestion
Can we Opt-Out .dark-mode somehow ? 
I dont think EVERYONE needs it and it adds a lot of load

**Comment by danny007in** [comment] 2021-05-05 16:43
Did in https://github.com/ColorlibHQ/AdminLTE/pull/3595
duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/3530
we will also do this in v4 AdminLTE

**Closed by danny007in** 2021-05-05 16:43 UTC
Labels: type:enhancement, version:4.x
