### ISSUE TITLE
Still bug in Logo

### ISSUE THREAD

**Issue by saileshkush95** [ColorlibHQ/AdminLTE#2170] opened 2019-07-15 14:21 UTC
### Issue type:
- [ ] Feature request 
- [x] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version:  V3
* Operating System:   Linux(Kde Neon)
* Browser (Version):  Latest Chrome

### Description:
I didn't know how to explain in short and sweet so I included giff. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28560875/61223213-fa8d8b00-a73b-11e9-9c32-95ed46d1f43a.gif)

**Comment by REJack** [comment] 2019-07-15 17:04
I can't replicate this issue in my local copy with changes, may I've fixed it already with 02c398e try my fork if this still appears.

**Comment by saileshkush95** [comment] 2019-07-16 02:40
This bug appears in dashboard2. 
You can produce this bug by expanding or collapsing dropdown item. As shown in below giff
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28560875/61261914-18daa180-a7a3-11e9-97eb-2fbba1b86a4b.gif)

**Comment by REJack** [comment] 2019-07-16 10:39
Oh that's caused by the ability to use the sidebar with tabs/:focus, I'll fix this soon.

**Comment by saileshkush95** [comment] 2019-07-16 14:10
Thanks for quick response

**Comment by REJack** [comment] 2019-07-16 14:28
Fixed in my PR #2169

**Comment by REJack** [comment] 2019-07-30 16:56
This issue is merged with my PR #2169

**Closed by REJack** 2019-07-30 16:56 UTC
Labels: Bug, css, v3
