### ISSUE TITLE
[QUESTION] Loses state on postback

### ISSUE THREAD

**Issue by mfkashani** [ColorlibHQ/AdminLTE#3337] opened 2021-01-20 17:24 UTC
I am not sure if this a feature request, a bug report or none of them but I am running into a problem and would appreciate some insight.
I implemented this in an ASP.NET master page and it works great on first page load. However, when I select a menu item, a postback occurs and the selected menu collapses and does not keep its state.
How would one deal with this issue?

Thank you.

**Comment by danny007in** [comment] 2021-01-20 20:04
Give some more details regarding issue like code, images, gifs to solve issue

**Comment by mfkashani** [comment] 2021-01-21 18:47
Hi Daniel
I used AdminLTE menu layout and scripts in an ASP.NET application's master
page. All pages in the application share this master page.
Every time a menu/sub-menu item is selected in this .NET application a
postback is done and the new page is fetched from the server. This means
the content of the master page is processed again which results in the menu
to go back to its original settings (all collapsed except "Dashboard"), no
matter what menu item was selected that resulted in the postback.

For example, initially you see "Dashboard V1", with the "Dashboard" menu
and "Dashboard V1" all selected.
Next I click on "Layout Options" to expand and select "Top Navigation".
This results in "topnav.aspx" file to be fetched (which includes codes/menu
from master page) and displayed.
When this is done, we go back to "Dashboard" and "Dashboard V1" being
selected and "Layout Options" loses focus/selection.

To make things clear as mud(!), I have attached screenshots that can be
viewed in order they are numbered.

I appreciate your help.

**Comment by kabutotx** [comment] 2021-01-22 06:46
You need class="nav-link active" on the dropped down menu.  You will need to know which menu you are on and add "active" to it.

**Comment by hareshpatel1990** [comment] 2021-01-22 09:06
Add following script at the end of every page, below code is work for me in PHP
```
<script type="text/javascript">
    $(document).ready(function(){
        var a = $('a[href="/current/page/url"]'); //You need to set dynamically target active link
        if (!a.parent().hasClass('treeview-menu') && !a.parent().parent().hasClass('pagination')) {
            a.parent().addClass('active');
            a.parent().parent().addClass('menu-open');
            a.parent().parent().show();
            // a.parent().addClass('active').parents('.treeview').addClass('active');
        }
    });
</script>
```

**Comment by danny007in** [comment] 2021-01-22 19:41
indirectly duplicate of https://github.com/ColorlibHQ/AdminLTE/issues/2068

**Closed** 2021-01-22 19:42 UTC
Labels: other:duplicate, type:question, version:3.x
