### ISSUE TITLE
Update font-awesome version

### ISSUE THREAD

**Issue by QuentinCurtet** [ColorlibHQ/AdminLTE#2318] opened 2019-10-10 09:29 UTC
- [x] Feature request 
- [ ] Bug report       
- [ ] Documentation   

### Environment:
* AdminLTE Version: 2.4.18
* Operating System:  Debian
* Browser (Version):  Chrome latest

### Description:
Is there any incompatibility to upgrade font-awesome to latest (5.11) ?
If not, is it possible to do it ?

Thanks in advance.

**Comment by REJack** [comment] 2019-10-10 10:29
In v2 I doesn't upgrade font-awesome to avoid possible breaks by users, I would need to create a complete new version (e.g. v2.5) but v2 will not recieve new features caused by v3 develop (v3 will soon released as stable).

But you can update/upgrade it by yourself without any problems (if you update it to the new css classes or using v4-shim), to get the correct sidebar toggle icon you only add `.fa5` to the `.sidebar-toggle`.

**Comment by QuentinCurtet** [comment] 2019-10-10 10:41
Ok thanks.

**Closed** 2019-10-16 07:10 UTC
